### PR TITLE
Feature: Adding prometheus monitoring

### PR DESCRIPTION
**Pull request by hypery2k**

### CODE REVIEW

**Comment by adferrand** [comment]
Hello @hypery2k ! Thanks a lot for your PR. It sounds good to me. The only thing I would like to retrieve the binary from a public source (bonus with a way to validate its authenticity, like a hash) or retrieve the source code and build it in place during the docker build. Is it possible ?

**Comment by hypery2k** [comment]
not really, maybe we could build it from here: https://github.com/otwieracz/backuppc_exporter
But it already took several steps to get it really build and if we build it via docker build we should at a integration test to ensure it's working afterwards

**Comment by christianuhlmann** [comment]
please consider whether it is not enough and it is better to wait for the new PR: https://github.com/backuppc/backuppc/pull/344

**Comment by adferrand** [comment]
New version 4.4.0 exposes the metrics added by BackupPC. I think this PR can be closed. If you think there is room for improvement, do not hesitate to open a new one!

**Pull request closed without merging**
